### ISSUE TITLE
[BUG] Spell Splinter-head arrow

### ISSUE THREAD

**Issue by OneZocom** [Xerney/Epic-War-4-Mod#2]
When casted the spell in battle it consume the mana, but nothing happened, no animation, no dmg, nothing.

Is there some extra requirments to cast it like some extra feature to unlock, or it is really bugged, because when i get it it would make sense to be able to use it. Thx for answer or fix.

**Comment by Xerney** [comment]
There is a small arrow that goes across the screen I have had many people tell me this in the discord but it is there :)
